# Generated by Django 4.2 on 2023-05-06 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery24', '0002_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCart',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='Stock',
            new_name='Product',
        ),
    ]
