# Generated by Django 4.2 on 2023-05-19 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery24', '0004_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reviews',
            new_name='Review',
        ),
    ]
