# Generated by Django 4.2 on 2023-05-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery24', '0005_rename_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
